### ISSUE TITLE
/mob copy command doesn't work

### ISSUE THREAD

**Issue by PentiumMMX166** [Dawn-of-Light/DOLSharp#224]
when i attempt to copy a mob, it simply doesn't work, nothing happens, no "Unknown mob" or anything.

**Comment by Nachtmahr91** [comment]
The Mob Copy command works without problems. You have to click on a mob first and then you type / mob copy.

**Comment by PentiumMMX166** [comment]
i clicked on a random mob (example: minor changeling) and typed /mob copy, same result, nothing. it's on the Eve of darkness DB. it works fine with a brand new mob that i created with no NPCtemplate.

**Comment by Nachtmahr91** [comment]
Okay, it's my mistake. I started the server with the newest version. It really doesn't work with the server version "1.109".

**Comment by PentiumMMX166** [comment]
when i try 1.125D, it just hangs for a while and then eventually says "Hit esc to exit game." so i use 1.109.

**Comment by Graveen** [comment]
Yes 1.125d is not really supported (or missing some parts). But in 1.109 it should work.
I'll test this !

**Comment by Graveen** [comment]
i can't reproduce with actual core and a non blank database (game.dll 1.109);
- plvl 3 toon
- /mob copy with selected mob working
- /mob create 
- /mob model 1000
- /mob copy with selected mob working
Be careful to be on MySQL database, not tested with SQLite or blank database.

**Comment by PentiumMMX166** [comment]
It only seems to happen with mobs in a NPCTemplate in the latest DOLserver program in client 1.109. copying works fine with mobs that don't have a NPC template, I reproduced it with /mob create and /mob model 97 and /mob copy, it worked fine.

**Comment by TheRealKataract** [comment]
This issue was corrected with a commit some days ago.
To reproduce the error you can create a mob and then do /reload mob (they will get the npctemplate 0 when reloaded). 
A check on the /mob copy command has been added to avoid the command trying to copy a npctemplate 0.

**Comment by PentiumMMX166** [comment]
I tried the latest DOLServer (1.9.7.3739) version with 1.109, same result, no mob appears when copying a mob with a NPCTemplate. I'm using the eve of darkness database.

**Comment by PentiumMMX166** [comment]
*sigh* no dice. still not working when i try to copy a mob with 1.109 with 1.9.7.3738.

**Comment by Graveen** [comment]
Do you have any error in the console ? Can you start from a blank db and let server create stuff ? Ty

**Comment by PentiumMMX166** [comment]
I also tried the Sniperwolf DB, same results, the only DOLserver that is stable is the really old 1.9.6.3061 setup version. Ill try a barebones SQLite db. see if any changes, and ill switch to the more stable 1.109 client.

**Comment by Nachtmahr91** [comment]
Install the database and the server according to these instructions: http://www.dolserver.net/viewtopic.php?f=4&t=23299

**Comment by PentiumMMX166** [comment]
there is no error in the console when i try mob copy with a NPCtemplate mob, nothing happens. it even happens in a barebones SQLite db. I created the mob, and assigned it to a NPCtemplate, and tried to copy it, nothing, not even an error on the server console. I'm on Windows 7, IDK if it might be to do with the OS.

**Comment by Graveen** [comment]
Ok i see what is wrong. @NetDwarf  fixed this in his PR.
